version: '3'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - ./run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 9000:9000
    networks:
      - local-portainer-net

networks:
  local-portainer-net:
    driver: bridge
